---
title: "R-Basic-Statistics"
author: "Meredith Franklin"
date: "21/10/2020"
output: html_document
---

We continue our tutorial using using [these
data](https://github.com/meredithfranklin/meredithfranklin.github.io/tree/master/data)
on jogging speed, distance and duration.  Now we will look at R commands to
generate basic summary statistics of variables in a dataset including
`mean()`, `median()`, `variance()`, `sum()`, `min()`, ` max()`, `range()`, and
`quantile()`.  We will also use the `dplyr` package to create summary
statistics by groups of variables in a dataset.

First, summary statistics of individual variables in a data.frame:

```r
jogging<-read.csv("sample_data_jogging.csv")
mean(jogging$jog_distance_mi)
```

    [1] 11.5

```r
median(jogging$jog_distance_mi)
```

    [1] 11

```r
var(jogging$jog_distance_mi)
```

    [1] 56.72222

```r
sum(jogging$jog_distance_mi)
```

    [1] 115

```r
min(jogging$jog_distance_mi)
```

    [1] 3

```r
max(jogging$jog_distance_mi)
```

    [1] 26

```r
range(jogging$jog_distance_mi)
```

    [1]  3 26

```r
quantile(jogging$jog_distance_mi)
```

       0%   25%   50%   75%  100% 
     3.00  5.50 11.00 14.75 26.00 

```r
quantile(jogging$jog_distance_mi,0.6)
```

     60% 
    12.8 

Many of these basic statistics, namely the mean, median, 25th and 75th
quartiles, min, and max, are automatically printed when the `summary()`
function is applied to a dataset.

```r
summary(jogging)
```

       subject_id     jog_time_hrs   jog_distance_mi
     Min.   : 1.00   Min.   :0.500   Min.   : 3.00  
     1st Qu.: 3.25   1st Qu.:1.250   1st Qu.: 5.50  
     Median : 5.50   Median :2.250   Median :11.00  
     Mean   : 5.50   Mean   :2.400   Mean   :11.50  
     3rd Qu.: 7.75   3rd Qu.:3.375   3rd Qu.:14.75  
     Max.   :10.00   Max.   :5.000   Max.   :26.00  

If we want to look at descriptive statistics by groups, the `dplyr`
package is very handy (and powerful). First,
`install.packages('dplyr')`. In our jogging dataset we don't have any
grouping variables, so let's create a gender variable which will be 1
for females and 0 for males.

```r
jogging$female<-c(1,0,0,1,0,1,1,1,0,0)
```

Now let's find summary statistics for jogging time and distance for
males and females using the `dplyr` package. First we create a grouped
dataset with `group_by(data, group)`.

```r
library(dplyr)
jogging_group <- group_by(jogging,female)
jogging_group
```

    Source: local data frame [10 x 4]
    Groups: female [2]

       subject_id jog_time_hrs jog_distance_mi female
            (int)        (dbl)           (int)  (dbl)
    1           1          2.0              10      1
    2           2          1.0               3      0
    3           3          3.5              15      0
    4           4          2.0               7      1
    5           5          3.0              14      0
    6           6          5.0              26      1
    7           7          1.0               5      1
    8           8          0.5               3      1
    9           9          3.5              20      0
    10         10          2.5              12      0

With this grouped dataset, we can easily get summary statistics for the
variables. In this case, we create a new summarized data.frame that has
an added count variable to indicate how many observations were in each
group, and then we take the mean of each of the variables in the
original dataset.

```r
jogging_group_summary <- summarize(jogging_group, count = n(), dist = mean(jog_distance_mi, na.rm = T), time = mean(jog_time_hrs, na.rm = T))
jogging_group_summary
```

    Source: local data frame [2 x 4]

      female count  dist  time
       (dbl) (int) (dbl) (dbl)
    1      0     5  12.8   2.7
    2      1     5  10.2   2.1

It is possible to summarize by more than one variable. Let's add another
grouping variable for age group to demonstrate this. Suppose age group 1
is individuals 30 or younger, age group 2 is individuals between 31 and
50 and age group 3 is individuals greater than 50.

```r
jogging$age<-c(1,2,3,1,2,3,1,2,3,1)
```

Create the grouped dataset and summarize the number of subjects (male or
female) in each age group (1,2 or 3).

```r
jogging_group2 <- group_by(jogging,female,age)
summarize(jogging_group2, count= n())
```

    Source: local data frame [6 x 3]
    Groups: female [?]

      female   age count
       (dbl) (dbl) (int)
    1      0     1     1
    2      0     2     2
    3      0     3     2
    4      1     1     3
    5      1     2     1
    6      1     3     1
