---
title: ""
author: "Meredith Franklin"
date: "21/10/2020"
output: html_document
---

### Research

- Spatial statistical methods for modeling and analyzing multi-scale
  spatial data and processes including: field measurements, remote
  sensing data, weather/climate model data, census data,
  transportation data.
- Development of functional regression models for dealing with spatial
  misalignment of environmental data.
- Epidemiological assessment of the human health impact associated
  with exposure to particulate matter air pollution and its chemical
  specific components.
- Spatio-temporal interpolation of observed, high-frequency climate
  data for the purpose of evaluating parameterizations and processes
  represented in global and regional climate models.
- Quantification of uncertainty in climate model outputs and
  propagation of this uncertainty when coupling climate to other
  physical models (hydrological, agricultural, economic).

### Publications

- [Google Scholar](https://scholar.google.com/citations?user=kIHe4WAAAAAJ)

### Contact

You can find me on
[LinkedIn](https://www.linkedin.com/in/meredithfranklin) and
github [\@meredithfranklin](https://github.com/meredithfranklin).
Or email me: [meredith.franklin\@usc.edu](mailto:support@github.com)
